app/blog/views/auth.py
from datetime import datetime

from flask import Blueprint, current_app, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from sqlalchemy.exc import IntegrityError

from ..extensions import db
from ..forms.users import LoginForm, RegistrationForm
from ..models.users import User

auth_app = Blueprint("auth_app", import_name=__name__, url_prefix="/auth", static_folder="../static")


@auth_app.route("/login/", methods=["GET", "POST"], endpoint="login")
def login():
    errors = []
    form = LoginForm(request.form)
    if request.method == "GET":
        if not current_user.is_authenticated:
            return render_template("auth/login.html", form=form, errors=errors)
        return redirect(url_for("index_app.root"))
    if form.validate_on_submit():
        if not form.username.data:
            errors.append("Username not passed")
        if not form.password.data:
            errors.append("Password not passed")
        user = User.query.filter_by(username=form.username.data).one_or_none()
        if user and user.validate_password(form.password.data):
            login_user(user)
            user.last_login = datetime.now()
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("index_app.root"))
        else:
            errors.append("Wrong credentials")
    return render_template("auth/login.html", form=form, errors=errors)


@auth_app.route("/logout/", endpoint="logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("index_app.root"))


@auth_app.route("/register/", endpoint="register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("index_app.root"))
    errors = []
    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).count():
            form.username.errors.append("username already exists!")
            return render_template("auth/register.html", form=form, errors=errors)
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists!")
            return render_template("auth/register.html", form=form, errors=errors)
        user_data = {
            "username": form.username.data,
            "fullname": form.fullname.data,
            "email": form.email.data,
            "password": form.password.data,
        }
        user = User(**user_data)
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            msg = "Could not create user!"
            current_app.logger.exception(msg)
            errors.append(msg)
        else:
            current_app.logger.info("Created user %s", user)
            login_user(user)
            user.last_login = datetime.now()
        return redirect(url_for("index_app.root"))
    return render_template("auth/register.html", form=form, errors=errors)


__all__ = [
    "auth_app",
]

app/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <title>
    {% block title %}
      Blog
    {% endblock %}
  </title>
  {% block css %}
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
  {% endblock %}
</head>

<body id="top" class="d-flex flex-column min-vh-100">
<main class="flex-shrink-0">
  {% block navbar %}
    {% include 'navbar.html' %}
  {% endblock %}

  {% block greeting %}
    <div class="container my-5">
      <h1>
        Hello,
        {% if current_user.is_authenticated %}
          {{ current_user.username }}!
        {% else %}
          anon!
        {% endif %}
      </h1>
    </div>
  {% endblock %}

  <div class="container my-5">
    {% block content %}
      Lorem ipsum...
    {% endblock %}
  </div>
</main>

{% block footer %}
  {% include 'footer.html' %}
{% endblock %}

{% block js %}
  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
{% endblock %}
</body>
</html>

app/blog/templates/footer.html
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.<br>Moscow, 2023</span>
  </div>
</footer>

app/blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('index_app.root') }}">
      <img src="{{ url_for('static', filename='images/logo.svg') }}" alt="Logo" width="30" height="24"
          class="d-inline-block align-text-top">
      {% block navbar_title %}
        Blog
      {% endblock %}
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% for (endpoint, label, show_item) in [
            ('articles_app.list', 'Articles', True),
            ('authors_app.list', 'Authors', True),
            ('users_app.list', 'Users', current_user.is_staff)
        ] %}
          {% if show_item %}
            <li class="nav-item">
              <a href="{{ url_for(endpoint) }}" class="nav-link{% if request.endpoint == endpoint %} active{% endif %}">
                {{ label }}
              </a>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <div class="navbar-nav ms-auto">
        {% if current_user.is_authenticated %}
          {% if current_user.is_staff %}
            <a class="nav-link" href="{{ url_for('admin.index') }}">Admin panel</a>
          {% endif %}
          <a class="nav-link" href="{{ url_for('users_app.details', pk=current_user.id) }}">
            {{ current_user.username | capitalize }}
          </a>
          <a class="nav-link" href="{{ url_for('auth_app.logout') }}">Logout</a>
        {% else %}
          <a href="{{ url_for('auth_app.login') }}"
              class="nav-link{% if request.endpoint == 'login' %} active{% endif %}">
            Login
          </a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>